slc6-gcc62:
    tags:
        - docker
    image: clicdp/slc6-base
    script:
        - export COMPILER_TYPE="gcc"
        - source .gitlab-ci.d/init_x86_64.sh
        - mkdir build
        - cd build
        - cmake -GNinja -DCMAKE_BUILD_TYPE=RELEASE -DGeant4_DIR=$G4LIB -DROOT_DIR=$ROOTSYS -DEigen3_DIR=$Eigen3_DIR ..
        - ninja
        - ninja install
        - ctest --output-on-failure -j4
        - cd ..
        - source $G4ENV_INIT
        - bin/allpix -c etc/example.conf


slc6-llvm39:
    tags:
        - docker
    image: clicdp/slc6-base
    script:
        - export COMPILER_TYPE="llvm"
        - source .gitlab-ci.d/init_x86_64.sh
        - mkdir build
        - cd build
        - cmake -GNinja -DCMAKE_BUILD_TYPE=RELEASE -DGeant4_DIR=$G4LIB -DROOT_DIR=$ROOTSYS -DEigen3_DIR=$Eigen3_DIR ..
        - ninja
        - ninja check-format
        - ninja check-lint
        - ninja install
        - ctest --output-on-failure -j4
        - cd ..
        - source $G4ENV_INIT
        - bin/allpix -c etc/example.conf

centos7-gcc62:
    tags:
        - docker
    image: clicdp/cc7-base
    script:
        - export COMPILER_TYPE="gcc"
        - source .gitlab-ci.d/init_x86_64.sh
        - mkdir build
        - cd build
        - cmake -GNinja -DCMAKE_BUILD_TYPE=RELEASE -DGeant4_DIR=$G4LIB -DROOT_DIR=$ROOTSYS -DEigen3_DIR=$Eigen3_DIR ..
        - ninja
        - ninja install
        - ctest --output-on-failure -j4
        - cd ..
        - source $G4ENV_INIT
        - bin/allpix -c etc/example.conf

centos7-llvm39:
    tags:
        - docker
    image: clicdp/slc6-base
    script:
        - export COMPILER_TYPE="llvm"
        - source .gitlab-ci.d/init_x86_64.sh
        - mkdir build
        - cd build
        - cmake -GNinja -DCMAKE_BUILD_TYPE=RELEASE -DGeant4_DIR=$G4LIB -DROOT_DIR=$ROOTSYS -DEigen3_DIR=$Eigen3_DIR ..
        - ninja
        - ninja check-format
        - ninja check-lint
        - ninja install
        - ctest --output-on-failure -j4
        - cd ..
        - source $G4ENV_INIT
        - bin/allpix -c etc/example.conf

mac1012-clang80:
    tags:
        - mac
    script:
        - source .gitlab-ci.d/init_mac.sh
        - mkdir build
        - cd build
        - cmake -GNinja -DCMAKE_BUILD_TYPE=RELEASE -DGeant4_DIR=$G4LIB -DROOT_DIR=$ROOTSYS -DEigen3_DIR=$Eigen3_DIR ..
        - ninja
        - ninja install
        - ctest --output-on-failure -j4
        - cd ..
        - source $G4ENV_INIT
        - bin/allpix -c etc/example.conf
