slc6-gcc62:
    tags:
        - docker
    image: clicdp/slc6-base
    script:
        - export COMPILER_TYPE="gcc"
        - source .gitlab-ci.d/init_x86_64.sh
        - mkdir build
        - cd build
        - cmake -GNinja -DGeant4_DIR=$G4INSTALL/lib64/Geant4-10.2.2 -DROOT_DIR=$ROOTSYS -DEigen3_DIR=$Eigen_HOME/lib64/cmake/eigen3 ..
        - ninja
        - ninja install
        - ctest --output-on-failure -j4
        - cd ..
        - source $G4ENV_INIT
        - bin/allpix etc/example_config.ini 


slc6-llvm39:
    tags:
        - docker
    image: clicdp/slc6-base
    script:
        - export COMPILER_TYPE="llvm"
        - source .gitlab-ci.d/init_x86_64.sh
        - mkdir build
        - cd build
        - cmake -GNinja -DGeant4_DIR=$G4INSTALL/lib64/Geant4-10.2.2 -DROOT_DIR=$ROOTSYS -DEigen3_DIR=$Eigen_HOME/lib64/cmake/eigen3 ..
        - ninja
        - ninja check-format
        - ninja check-lint
        - ninja install
        - ctest --output-on-failure -j4
        - cd ..
        - source $G4ENV_INIT
        - bin/allpix etc/example_config.ini 

centos7-gcc62:
    tags:
        - docker
    image: clicdp/cc7-base
    script:
        - export COMPILER_TYPE="gcc"
        - source .gitlab-ci.d/init_x86_64.sh
        - mkdir build
        - cd build
        - cmake -GNinja -DGeant4_DIR=$G4INSTALL/lib64/Geant4-10.2.2 -DROOT_DIR=$ROOTSYS -DEigen3_DIR=$Eigen_HOME/lib64/cmake/eigen3 ..
        - ninja
        - ninja install
        - ctest --output-on-failure -j4
        - cd ..
        - source $G4ENV_INIT
        - bin/allpix etc/example_config.ini 

centos7-llvm39:
    tags:
        - docker
    image: clicdp/slc6-base
    script:
        - export COMPILER_TYPE="llvm"
        - source .gitlab-ci.d/init_x86_64.sh
        - mkdir build
        - cd build
        - cmake -GNinja -DGeant4_DIR=$G4INSTALL/lib64/Geant4-10.2.2 -DROOT_DIR=$ROOTSYS -DEigen3_DIR=$Eigen_HOME/lib64/cmake/eigen3 ..
        - ninja
        - ninja check-format
        - ninja check-lint
        - ninja install
        - ctest --output-on-failure -j4
        - cd ..
        - source $G4ENV_INIT
        - bin/allpix etc/example_config.ini 
    
mac1012-clang80:
    tags:
        - mac
    script:
        - source .gitlab-ci.d/init_x86_64.sh
        - mkdir build
        - cd build
        - cmake -GNinja -DGeant4_DIR=$G4INSTALL/lib/Geant4-10.2.2 -DROOT_DIR=$ROOTSYS -DEigen3_DIR=$Eigen_HOME/lib64/cmake/eigen3 ..
        - ninja
        - ninja install
        - ctest --output-on-failure -j4
        - cd ..
        - source $G4ENV_INIT
        - bin/allpix etc/example_config.ini 
