variables:
    EOS_PATH: "/eos/project/a/allpix-squared/www/"

stages:
    - compile
    - unittest
    - format
    - documentation
    - deploy

#######################
# Compilation targets #
#######################

cmp:slc6-gcc:
    stage: compile
    tags:
        - docker
    image: clicdp/slc6-base
    script:
        - export COMPILER_TYPE="gcc"
        - source .gitlab-ci.d/init_x86_64.sh
        - source .gitlab-ci.d/load_deps.sh
        - mkdir build
        - cd build
        - cmake -GNinja -DBUILD_ALL_MODULES=ON -DCMAKE_BUILD_TYPE=RELEASE -DGeant4_DIR=$G4LIB -DROOT_DIR=$ROOTSYS -DEigen3_DIR=$Eigen3_DIR ..
        - ninja
        - ninja install
    artifacts:
        paths:
            - build
            - bin
            - lib
        expire_in: 3 hour

cmp:slc6-llvm:
    stage: compile
    tags:
        - docker
    image: clicdp/slc6-base
    script:
        - export COMPILER_TYPE="llvm"
        - source .gitlab-ci.d/init_x86_64.sh
        - mkdir build
        - cd build
        - cmake -GNinja -DBUILD_ALL_MODULES=ON -DCMAKE_BUILD_TYPE=RELEASE -DGeant4_DIR=$G4LIB -DROOT_DIR=$ROOTSYS -DEigen3_DIR=$Eigen3_DIR ..
        - ninja
        - ninja install
    artifacts:
        paths:
            - build
            - bin
            - lib
        expire_in: 3 hour

# Ensure that our LXPLUS setup script is functional:
cmp:lxplus-gcc:
    stage: compile
    tags:
        - docker
    image: clicdp/slc6-base
    script:
        - export COMPILER_TYPE="gcc"
        - source etc/scripts/setup_lxplus.sh
        - mkdir build
        - cd build
        - cmake -GNinja -DBUILD_ALL_MODULES=ON -DCMAKE_BUILD_TYPE=RELEASE ..
        - ninja
        - ninja install
    artifacts:
        paths:
            - build
            - bin
            - lib
        expire_in: 3 hour

cmp:cc7-gcc:
    stage: compile
    tags:
        - docker
    image: clicdp/cc7-base
    script:
        - export COMPILER_TYPE="gcc"
        - source .gitlab-ci.d/init_x86_64.sh
        - source .gitlab-ci.d/load_deps.sh
        - mkdir build
        - cd build
        - cmake -GNinja -DBUILD_ALL_MODULES=ON -DCMAKE_BUILD_TYPE=RELEASE -DGeant4_DIR=$G4LIB -DROOT_DIR=$ROOTSYS -DEigen3_DIR=$Eigen3_DIR ..
        - ninja
        - ninja install
    artifacts:
        paths:
            - build
            - bin
            - lib
        expire_in: 3 hour

cmp:cc7-llvm:
    stage: compile
    tags:
        - docker
    image: clicdp/cc7-base
    script:
        - export COMPILER_TYPE="llvm"
        - source .gitlab-ci.d/init_x86_64.sh
        - mkdir build
        - cd build
        - cmake -GNinja -DBUILD_ALL_MODULES=ON -DCMAKE_BUILD_TYPE=RELEASE -DGeant4_DIR=$G4LIB -DROOT_DIR=$ROOTSYS -DEigen3_DIR=$Eigen3_DIR ..
        - ninja
        - ninja install
    artifacts:
        paths:
            - build
            - bin
            - lib
        expire_in: 3 hour

cmp:mac1012-clang:
    stage: compile
    tags:
        - mac
    script:
        - source .gitlab-ci.d/init_mac.sh
        - source .gitlab-ci.d/load_deps.sh
        - mkdir build
        - cd build
        - cmake -GNinja -DBUILD_ALL_MODULES=ON -DCMAKE_BUILD_TYPE=RELEASE -DGeant4_DIR=$G4LIB -DROOT_DIR=$ROOTSYS -DEigen3_DIR=$Eigen3_DIR -DCMAKE_USE_RELATIVE_PATHS=TRUE ..
        - ninja
        - ninja install
    artifacts:
        paths:
            - build
            - bin
            - lib
        expire_in: 3 hour



############################
# Format and Lint Checking #
############################

# SLC 6

fmt:slc6-llvm-format:
    stage: format
    tags:
        - docker
    dependencies:
        - cmp:slc6-llvm
    image: clicdp/slc6-base
    script:
        - export COMPILER_TYPE="llvm"
        - source .gitlab-ci.d/init_x86_64.sh
        - cd build/
        - ninja check-format

fmt:slc6-llvm-lint:
    stage: format
    tags:
        - docker
    dependencies:
        - cmp:slc6-llvm
    image: clicdp/slc6-base
    script:
        - export COMPILER_TYPE="llvm"
        - source .gitlab-ci.d/init_x86_64.sh
        - cd build/
        - ninja check-lint


# CentOS 7

fmt:cc7-llvm-format:
    stage: format
    tags:
        - docker
    dependencies:
        - cmp:cc7-llvm
    image: clicdp/cc7-base
    script:
        - export COMPILER_TYPE="llvm"
        - source .gitlab-ci.d/init_x86_64.sh
        - cd build/
        - ninja check-format

fmt:cc7-llvm-lint:
    stage: format
    tags:
        - docker
    dependencies:
        - cmp:cc7-llvm
    image: clicdp/cc7-base
    script:
        - export COMPILER_TYPE="llvm"
        - source .gitlab-ci.d/init_x86_64.sh
        - cd build/
        - ninja check-lint



##############
# Unit tests #
##############

# SLC 6

mod:slc6-gcc:
    stage: unittest
    tags:
        - docker
    dependencies:
        - cmp:slc6-gcc
    image: clicdp/slc6-base
    script:
        - source .gitlab-ci.d/init_x86_64.sh
        - cd build/
        - ctest -R test_modules --output-on-failure -j4

mod:lxplus-gcc:
    stage: unittest
    tags:
        - docker
    dependencies:
        - cmp:lxplus-gcc
    image: clicdp/slc6-base
    script:
        - source etc/scripts/setup_lxplus.sh
        - cd build/
        - ctest -R test_modules --output-on-failure -j4

mod:slc6-llvm:
    stage: unittest
    tags:
        - docker
    dependencies:
        - cmp:slc6-gcc
    image: clicdp/slc6-base
    script:
        - export COMPILER_TYPE="llvm"
        - source .gitlab-ci.d/init_x86_64.sh
        - cd build/
        - ctest -R test_modules --output-on-failure -j4


# CentOS 7

mod:cc7-gcc:
    stage: unittest
    tags:
        - docker
    dependencies:
        - cmp:cc7-gcc
    image: clicdp/cc7-base
    script:
        - source .gitlab-ci.d/init_x86_64.sh
        - source .gitlab-ci.d/load_deps.sh
        - cd build/
        - ctest -R test_modules --output-on-failure -j4

mod:cc7-llvm:
    stage: unittest
    tags:
        - docker
    dependencies:
        - cmp:cc7-llvm
    image: clicdp/cc7-base
    script:
        - export COMPILER_TYPE="llvm"
        - source .gitlab-ci.d/init_x86_64.sh
        - cd build/
        - ctest -R test_modules --output-on-failure -j4


# Mac OS X

mod:mac1012-clang:
    stage: unittest
    tags:
        - mac
    dependencies:
        - cmp:mac1012-clang
    script:
        - source .gitlab-ci.d/init_mac.sh
        - source .gitlab-ci.d/load_deps.sh
        - cd build/
        - cmake -DTEST_MODULES=OFF ..
        - ctest -R test_modules --output-on-failure -j4


# SLC 6

perf:slc6-gcc:
    stage: unittest
    tags:
        - docker
    dependencies:
        - cmp:slc6-gcc
    image: clicdp/slc6-base
    script:
        - source .gitlab-ci.d/init_x86_64.sh
        - cd build/
        - ctest -R test_performance --output-on-failure -j4

perf:lxplus-gcc:
    stage: unittest
    tags:
        - docker
    dependencies:
        - cmp:lxplus-gcc
    image: clicdp/slc6-base
    script:
        - source etc/scripts/setup_lxplus.sh
        - cd build/
        - ctest -R test_performance --output-on-failure -j4

perf:slc6-llvm:
    stage: unittest
    tags:
        - docker
    dependencies:
        - cmp:slc6-gcc
    image: clicdp/slc6-base
    script:
        - export COMPILER_TYPE="llvm"
        - source .gitlab-ci.d/init_x86_64.sh
        - cd build/
        - ctest -R test_performance --output-on-failure -j4


# CentOS 7

perf:cc7-gcc:
    stage: unittest
    tags:
        - docker
    dependencies:
        - cmp:cc7-gcc
    image: clicdp/cc7-base
    script:
        - source .gitlab-ci.d/init_x86_64.sh
        - source .gitlab-ci.d/load_deps.sh
        - cd build/
        - ctest -R test_performance --output-on-failure -j4

perf:cc7-llvm:
    stage: unittest
    tags:
        - docker
    dependencies:
        - cmp:cc7-llvm
    image: clicdp/cc7-base
    script:
        - export COMPILER_TYPE="llvm"
        - source .gitlab-ci.d/init_x86_64.sh
        - cd build/
        - ctest -R test_performance --output-on-failure -j4


# Mac OS X

perf:mac1012-clang:
    stage: unittest
    tags:
        - mac
    dependencies:
        - cmp:mac1012-clang
    script:
        - source .gitlab-ci.d/init_mac.sh
        - source .gitlab-ci.d/load_deps.sh
        - cd build/
        - cmake -DTEST_MODULES=OFF ..
        - ctest -R test_performance --output-on-failure -j4



#############################
# Documentation Compilation #
#############################


# Compile Doxygen reference
cmp:doxygen:
    stage: documentation
    tags:
        - docker
    image: clicdp/cc7-base
    dependencies: []
    script:
        - source .gitlab-ci.d/init_x86_64.sh
        - source .gitlab-ci.d/load_deps.sh
        - mkdir -p public/usermanual
        - mkdir build
        - cd build
        - cmake -DBUILD_DOCS_ONLY=ON ..
        - make reference
        - mv reference/html ../public/reference
    artifacts:
        paths:
            - public
        expire_in: 3 hour

# Compile LaTeX user manual:
cmp:usermanual:
    stage: documentation
    tags:
      - docker
    image: gitlab-registry.cern.ch/clicdp/publications/templates/custom_ci_worker:fedora-latex-latest
    dependencies: []
    script:
        - mkdir -p public/usermanual
        - mkdir build
        - cd build
        - cmake -DBUILD_DOCS_ONLY=ON ..
        - make pdf
        - make html
        - mv usermanual/*.html ../public/usermanual
        - mv usermanual/*.css ../public/usermanual
        - mv usermanual/logo.png ../public/usermanual
        - mv usermanual/allpix-manual.pdf ../public/usermanual
        - mkdir -p ../public/usermanual/usermanual/
        - mkdir -p ../public/usermanual/usermanual/html/
        - mv usermanual/usermanual/html/css ../public/usermanual/usermanual/html/
        - mv usermanual/usermanual/html/js ../public/usermanual/usermanual/html/
        - mv usermanual/usermanual/figures ../public/usermanual/usermanual/
    artifacts:
        paths:
          - public
        expire_in: 3 hour



############################
# Documentation Deployment #
############################

# Automatically deploy documentation to the website
# Deployment job only executed for new tag pushs, not for every commit.
deploy-documentation:
    stage: deploy
    tags:
      - docker
    # Only run for new tags:
    only:
        - tags
        - test-deploy
    dependencies:
        - cmp:usermanual
        - cmp:doxygen
    # Docker image with tools to deploy to EOS
    image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer:latest
    script:
        - deploy-eos
    # do not run any globally defined before_script or after_script for this step
    before_script: []
    after_script: []
